### ISSUE TITLE
Need for an isolated testing envionment?

### ISSUE THREAD

**Issue by leesh3288** [KAIST-CS220/FsClassRoom#12]
It seems that the sanitization logic is still not complete for various AST cases, ranging from the obvious `SynExpr.Lambda` to seemingly unproblematic cases, for example `SynMemberDefn.ValField` where a rogue typed val field can be abused through the type system to circumvent identifier checks.

However, what I claim is that rather than sanitizing code based on blacklists, it would be much better to test codes in an isolated environment, for example dockerized environments, AppContainers or integrity levels / DACLs in Windows environment. This is because blacklist-based filtering, even with rigorous sanitization, are prone to various pitfalls.

Take for example, a sanitization routine that simply filters out any existing `"System"` text inside code, a very extreme sanitization rule not even allowing `"System"` to be written inside comment section. While this method seems excessive (not to mention false positives), there are still ways to bypass the check. Using reflection without needing to actually include `open System.Reflection`, we can use any type or methods inside System namespace without even writing `"System"` inside code.

It is probably possible to ban the use of reflective features through blacklisting all relevant methods or using typed AST to filter out any use of `System.Type`, but at this level I assume we're simply killing the F# language. Using isolated testing environments instead would provide proper protection on the testing server.

This feature would be good for the sake of completeness, but I wonder if this would be overkill for an in-class educational platform?

**Comment by sangkilc** [comment]
This is a fundamental problem in secure design, and blacklisting can never be the perfect solution as you said. On the other hand, sandboxing requires more computation power as we need to handle 100+ simultaneous requests. As for the purpose of CS220, black-box approach is more than enough. However, if you want to create a real-world service, than you should really go for the sandboxing approach.
