### ISSUE TITLE
Fantastic project!

### ISSUE THREAD

**Issue by ryepesg** [KAIST-CS220/FsClassRoom#13]
This project looks amazing! Is there a website where I could practice with the F# problems you have created? Are security related exercises also?

Keep on the good work!

**Comment by sangkilc** [comment]
Thanks for your interest. You can see some here: https://github.com/KAIST-CS220/2020s-activities

**Comment by ryepesg** [comment]
Excellent, thanks for that. When I try to run the server I get:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.0.0' was not found.
  - The following frameworks were found:
      5.0.2 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

I tried to install .NET Core 3, but I found: `This release has reached end of life, meaning it is no longer supported. We recommend moving to a supported release`.

I am not using Windows, so it is not easy for me to recompile the project for .NET 5. I will try running the tests locally instead.

Thank you.
